{application,log,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{log_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[config,db_log,lib_db,log,log_app,log_server,log_sup]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
